BROKER_URL = 'amqp://localhost'

CELERY_RESULT_BACKEND = 'redis://localhost'

# CELERY_TASK_SERIALIZER = 'json'
CELERY_TASK_SERIALIZER = 'pickle'
CELERY_RESULT_SERIALIZER = 'json'
# CELERY_TASK_RESULT_EXPIRES = 60 * 60 * 24
CELERYD_CONCURRENCY = 1
CELERY_CREATE_MISSING_QUEUES = True

CELERY_DEFAULT_EXCHANGE = 'xxx'
CELERY_DEFAULT_EXCHANGE_TYPE = 'direct'
# CELERY_DEFAULT_EXCHANGE_TYPE = 'topic'
CELERY_DEFAULT_ROUTING_KEY = 'xxx.default'

CELERY_ACKS_LATE = True
CELERYD_PREFETCH_MULTIPLIER = 1  # in common the value is same with count of core in cpu.  default 4

# CELERY_ACCEPT_CONTENT = ['json', ]
CELERY_ACCEPT_CONTENT = ['pickle', 'json']
BROKER_POOL_LIMIT = 1000
